name: Codeception tests

on: [push]

jobs:
  build:
    name: ${{matrix.operating-system}}, PHP ${{ matrix.php }}, Redis ${{matrix.redis-version}}
    
    runs-on: ${{ matrix.operating-system }}
    
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, ubuntu-20.04 ]
        php: [ '7.4', '8.0' ]
        redis-version: [4, 5, 6]
    
    steps:
      - uses: actions/checkout@master
      
      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}
        
      - name: Install dependencies
        run: composer install 
      
      - name: Run tests
        run: php vendor/bin/codecept run 
